### ISSUE TITLE
Phonegap application killed by Android when Wi-Fi is turned off.

### ISSUE THREAD

**Issue by radek-anuszewski** [vstirbu/ZeroConf#19]
In my company I use `cordova-zeroconf-plugin` to detect available devices and I am very happy because everything works very well, except one thing: when Wi-Fi is turned off, application is stopped by Android right after start. 
What astonishing, when Wi-Fi is turned on (even without connection, e.g. there's no any Wi-Fi available) everything works. When I debug app with Chrome Dev Tools, just before moment when app will be killed I get in console:
```
deviceready has not fired after 5 seconds. cordova.js:1183
Channel not fired: onFileSystemPathsReady cordova.js:1176
Received Event: deviceready
```
I include plugin in `config.xml` in this way: 
`<gap:plugin name="cordova-zeroconf-plugin" source="npm" />
`
Thank you in advance for looking on this problem, if any further details will be needed please write - I will provide them expeditiously.

**Comment by vstirbu** [comment]
Can you post the log from logcat (e.g. the section that have ZeroConf.java in it).

**Comment by DQ92** [comment]
I am work with @radek-anuszewski and we create very simple project:
http://www10.zippyshare.com/v/rEzwvue3/file.html

Error caused by ZeroConf.watch function. We havent access to log from logcat.
Thank you in advance for looking on this problem.

**Comment by vstirbu** [comment]
I cannot replicate this behaviour with WiFi turned off or withoutWifI in emulator using Android 4.4/5.0/6.0. Can you provide more information about your environment?

**Comment by DQ92** [comment]
When we test our app we using real devices: Nexus 4 with Android 4.4.4, Samsung GT-I9105P Android 4.2.2, Motorola Moto G2 Android 5.0.2. It is important, that on device must be WiFi turned off and Data Transmission (GSM) too. Today we tested on emulator with Android 5.0.2 and everything works. So, if you want to replicate this error you should use real device.
