### ISSUE TITLE
Services not getting discovered when Android is in Hotspot mode

### ISSUE THREAD

**Issue by emiliojazz** [vstirbu/ZeroConf#20]
ZeroConf works ok when Android device is connected to an existing Wifi network, but it fails to discover services (watch) when it is in Hotspot mode and there are devices connected to it.
Looks like multicast is getting filtered from hotspot?

**Comment by vstirbu** [comment]
If the access point providing the hotspot service is configured to filter multicast messages from the attached stations there is nothing you can do about it.

**Comment by emiliojazz** [comment]
Maybe I do not explained the problem well...with Hotspot mode I intend the Android device put in Wifi tethering mode (connected to Internet via cellular, sharing connection via Wifi)...so basically Android acting as an hotspot...any ideas, clues?

**Comment by vstirbu** [comment]
Can you give more details on the sequence of events that leads to this? Are you connected to any WiFi network before switching to mobile hotspot? etc?

**Comment by vstirbu** [comment]
The plugin does not handle changes in the network configuration. You might want to listen to changes using the standard network info plugin and re-register your zeroconf interests.

**Comment by phanirithvij** [comment]
No, It is just the mobile hotspot there are no network changes involved.

**Comment by dustinkerstein** [comment]
@emiliojazz were you ever able to get zeroconf working with Android providing a hotspot?

**Comment by vstirbu** [comment]
There are two network interfaces in the hotspot scenario. Currently, the plugin finds the [first ipv4 address](https://github.com/vstirbu/ZeroConf/blob/master/src/android/ZeroConf.java#L311-L330), which might not be the one in the hotspot.

The plugin functionality needs to be enhanced to bind on all network interfaces in order to work reliably with hotspots.
