### ISSUE TITLE
mdns and maven error while installing plugin

### ISSUE THREAD

**Issue by cajay01** [vstirbu/ZeroConf#21]
add to body class: platform-android
ANDROID_HOME=D:\csetups\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.7.0_79
No target specified, deploying to device '4d0081304bf041af'.

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'android'.
  
  > Could not resolve all dependencies for configuration ':_debugCompile'.
  > Could not resolve javax.jmdns:jmdns:+.
  >  Required by:
  >      :android:unspecified
  > Failed to list versions for javax.jmdns:jmdns.
  >      > Unable to load Maven meta-data from https://repo1.maven.org/maven2/ja
  > vax/jmdns/jmdns/maven-metadata.xml.
  >         > Could not GET 'https://repo1.maven.org/maven2/javax/jmdns/jmdns/ma
  > ven-metadata.xml'.
  >            > Connection to https://repo1.maven.org refused
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

**Comment by vstirbu** [comment]
Seems like a maven issue in your environment (`Connection to https://repo1.maven.org refused`). Are you behind a proxy? The `jmdns` package is available there if going by browser.

**Comment by cajay01** [comment]
yes ,I am behind the proxy

**Comment by vstirbu** [comment]
follow the instructions here: http://maven.apache.org/guides/mini/guide-proxies.html

**Comment by cajay01** [comment]
hey I got access to open nw but after that I got errorin util package

:compileDebugJavaWithJavacandroid\src\com\triggertrap\ZeroConf.java:31: error: package org.apache.http.conn.util does not exist
import org.apache.http.conn.util.InetAddressUtils;
                                ^
 FAILED

BUILD FAILED

**Comment by vstirbu** [comment]
try this: https://github.com/macdonst/cordova-plugin-zeroconf/commit/dad0f3ce6f2794300a904c1eb57b69886754c139

**Comment by cajay01** [comment]
Done..
Thank you!!!

**Comment by cajay01** [comment]
hey I am facing new issue  of legacy.jar file

Installing "cordova-zeroconf-plugin" for android
Failed to install 'cordova-zeroconf-plugin':Uh oh!
"D:\Projects\ProximityProfile\Mobile Application\Source Code\Android\plugins\cordova-zeroconf-plugin\src\android\libs\org.apache.http.legacy.jar" not found!

**Comment by vstirbu** [comment]
Browse the fork that I've indicated earlier and copy the jar. Is in the second/Android/libs
