### ISSUE TITLE
Calling close let other calls crash

### ISSUE THREAD

**Issue by StefanFu** [vstirbu/ZeroConf#22]
Hi,

In my app I'm searching for device with _ZeroConf.watch(...)._  After a timeout I called _ZeroConf.close()_ to stop the service. When I now try to call the _ZeroConf.watch(...)_ again the app crashes. The reason for that is that in ZeroConf.java the jmdns is not set to null.

Here my fix which is working:
...
        } else if (action.equals("close")) {
            if (jmdns != null) {
                try {
                    jmdns.close();
                } catch (IOException e) {
                    e.printStackTrace();
                } finally {
                    jmdns = null;
                }
            }
        } else if (action.equals("unregister")) {
...

I can call unwatch and than it's working. But when I change the WLAN the I cannot find devices in the new network because we initialize the ZeroConf with an IP.

**Comment by StefanFu** [comment]
By the way the method close() can block for a long time. Should may also run in a separate Runnable

**Comment by vstirbu** [comment]
Android growing up pains are visible all over this plugin. It has not been updated for a long time and definitely improvements should be brought in, and in fact would be welcome.

**Comment by StefanFu** [comment]
I forked the project and pushed my changes. Feel free to merge it or can/should I do that?

**Comment by vstirbu** [comment]
Thanks for fixing this issue. If you make a pull request I'll merge it and publish an update in npm.
