### ISSUE TITLE
Can't find my http server on network

### ISSUE THREAD

**Issue by laughinglion** [vstirbu/ZeroConf#24]
Hi, I'm trying to detect my http web service broadcasted on my network, but the watch callback is never fired:
ZeroConf.watch('_http._tcp.local.', function (result) { console.log('ecs ' + JSON.stringify(result)); });

Android Studio console shows:
07-13 09:18:40.469 4281-4281/za.co.myapp.print V/ZeroConf: Initialized
07-13 09:18:41.443 4281-4338/za.co.myapp.print D/ZeroConf: Setup watcher
07-13 09:18:41.452 4281-4338/za.co.myapp.print D/ZeroConf: Watch _http._tcp.local.
07-13 09:18:41.452 4281-4338/za.co.myapp.print D/ZeroConf: Name: 192-168-83-101.local. host: 192-168-83-101.local.

I can see it advertised if I use the dns-sd tool:
dns-sd -Z _http._tcp

_http._tcp                                      PTR     Corne2-PC._http._tcp
Corne2-PC._http._tcp                            SRV     0 0 8080 Corne2-PC.local. ; Replace with unicast FQDN of target host
Corne2-PC._http._tcp                            TXT     "product=Print Server API 0.1.0 "

The web server is on nodejs and advertised with:
var ad2 = mdns.createAdvertisement(mdns.tcp('http'), 8080, {txtRecord: {product: 'Print Server API 0.1.0 '}});
ad2.start();

Any suggestions?

**Comment by vstirbu** [comment]
Can you provide more info about your setup, e.g. device used, network configuration, etc.?

Are you able to see the service using something like this: https://play.google.com/store/apps/details?id=com.melloware.zeroconf&hl=en?

**Comment by laughinglion** [comment]
Hi, sorry for late reply. 

I tried the library from my Samsung S5 phone and Nexus 7 2012 tablet.

I tried the app above in the link you gave with my Samsung phone and it successfully finds my custom http server as well as my custom ipp service.

The service runs on my computer which is wirelessly connected to my Internet router, the phone connects to the same wifi network.

**Comment by jcrosby10** [comment]
I am having the same issue, my callback is not being called. My log is showing 

```03-07 14:50:42.686 6401-6503/? D/ZeroConf: Addresses [/fe80::d85b:2aff:fe48:3df5%p2p0%8]
03-07 14:50:42.686 6401-6503/? D/ZeroConf: Hostname android-64aa88813184d8e6
03-07 14:50:42.686 6401-6503/? V/ZeroConf: Initialized
03-07 14:50:42.686 6401-6503/? D/ZeroConf: Watch _http._tcp.

**Comment by vstirbu** [comment]
`timakeystore.jar` is not part of this plugin.

**Comment by jcrosby10** [comment]
Yes I am not worried about that line. Its the 3 above because my callback is never called with a result. I just did a search in the log for zeroconf and this is what was shown. It appears that the code is initializing and starts the process of watching. But I never get a response back.

**Comment by jcrosby10** [comment]
I updated the comment to be more relevant.

**Comment by vstirbu** [comment]
The plugin works only when you have network interfaces supporting multicast. Cellular is not one of them. What network interfaces you have active?

**Comment by jcrosby10** [comment]
My tablet is connected to a wifi network. There is a another device on that network I need to scan for and detect it. This app was originally set up to use the npm module [bonjour](https://github.com/watson/bonjour) which is another multicast detection service. So this should work. I had to switch because bonjour doesn't work on mobile.

**Comment by jcrosby10** [comment]
Well I found out somehow I am using a different plugin. [cordova-plugin-zeroconf](https://github.com/becvert/cordova-plugin-zeroconf). I was searching Google and found this and thought it was the same plugin as the names are very similar.

**Comment by vstirbu** [comment]
Over reliance on Google, it seems... but now that you are here, you can use plugin that actually works 😁
